name: Build Lambdas

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
permissions:
  id-token: write
  contents: read

jobs:
  buildLambdas:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      lambda-names: ${{ steps.get-lambdas.outputs.names }}
    steps:
      - uses: actions/checkout@v3


      - uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Infra dependencies
        run: npm install 

      - name: Build Lambdas
        run: |
          npx sls package

      - name: Make directory for lambdas
        run: |
          mkdir -p lambdas
          cp ./.serverless/*.zip lambdas/

      - name: Upload Lambda folder
        uses: actions/upload-artifact@v4
        with:
          name: lambda-folder
          path: lambdas/

      - name: Get Lambda names
        id: get-lambdas
        run: |
          mkdir -p lambdas
          LAMBDA_ARRAY=()
          for f in lambdas/*.zip; do
            [ -e "$f" ] || continue
            FILE=$(basename "$f")

            NAME="${FILE%.zip}"

            LAMBDA_ARRAY+=("\"$NAME\"")
          done
          IFS=,
          JSON="[${LAMBDA_ARRAY[*]}]"
          echo "names=$JSON" >> $GITHUB_OUTPUT
          echo $JSON
  LambdaToS3:
    needs: buildLambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ${{ fromJSON(needs.buildLambdas.outputs.lambda-names) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Lambda folder
        uses: actions/download-artifact@v4
        with:
          name: lambda-folder
          path: lambdas/

      - name: Assume federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federated
      - name: Assume worker role (chained)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_WORKER_ROLE_ARN }}
          role-chaining: true
          role-session-name: Worker

      
      - name: Install OpenTofu
        run: |
          curl -fsSL https://get.opentofu.org/install-opentofu.sh \
            | sh -s -- --install-method standalone
          echo "/opt/opentofu/bin" >> $GITHUB_PATH
          tofu version

      - name: Set TF_VAR_file_name
        run: |
          export TF_VAR_file_name=${{ matrix.lambda }}
          echo "TF_VAR_file_name=${{ matrix.lambda }}" >> $GITHUB_ENV

      - name: Get GitHub version
        id: get-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Set TF_VAR_folder_name
        run: |
          echo "TF_VAR_state_bucket_name=${{ secrets.STATE_BUCKET_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_bucket_name=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_region=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

      - name: Set stack name
        run: |
          echo "STACK_NAME=${{ matrix.lambda }}" >> $GITHUB_ENV


      - name: Init OpenTofu
        run: |
          cd infra/
          export TF_VAR_region=${{ vars.AWS_REGION }}
          export TF_VAR_file_name=${{ matrix.lambda }}
          export TF_VAR_state_bucket_name=${{ secrets.STATE_BUCKET_NAME }}
          export TF_VAR_bucket_name=${{ secrets.BUCKET_NAME }}
          export TF_STATE="dev/${{ matrix.lambda }}/terraform.tfstate"
          tofu init
          tofo plan
      - name: Deploy Lambda
        run: |
          cd infra
          tofu apply -auto-approve \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" 
