name: Build Lambdas

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
permissions:
  id-token: write
  contents: read

jobs:
  buildLambdas:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      lambda-names: ${{ steps.get-lambdas.outputs.names }}
    steps:
      - uses: actions/checkout@v3


      - uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Infra dependencies
        run: npm install 

      - name: Build Lambdas
        run: |
          npx sls package

      - name: Make directory for lambdas
        run: |
          mkdir -p lambdas
          cp ./.serverless/*.zip lambdas/

      - name: Upload Lambda folder
        uses: actions/upload-artifact@v4
        with:
          name: lambda-folder
          path: lambdas/

      - name: Get Lambda names
        id: get-lambdas
        run: |
          mkdir -p lambdas
          LAMBDA_ARRAY=()
          for f in lambdas/*.zip; do
            [ -e "$f" ] || continue
            FILE=$(basename "$f")

            NAME="${FILE%.zip}"

            LAMBDA_ARRAY+=("\"$NAME\"")
          done
          IFS=,
          JSON="[${LAMBDA_ARRAY[*]}]"
          echo "names=$JSON" >> $GITHUB_OUTPUT
          echo $JSON
  LambdaToS3:
    needs: buildLambdas
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda: ${{ fromJSON(needs.buildLambdas.outputs.lambda-names) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Lambda folder
        uses: actions/download-artifact@v4
        with:
          name: lambda-folder
          path: lambdas/

      - name: Assume federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federated
      - name: Assume worker role (chained)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_WORKER_ROLE_ARN }}
          role-chaining: true
          role-session-name: Worker

      
      - name: Install OpenTofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method deb
          rm -f install-opentofu.sh
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://get.opentofu.org/opentofu.gpg | sudo tee /etc/apt/keyrings/opentofu.gpg >/dev/null
          curl -fsSL https://packages.opentofu.org/opentofu/tofu/gpgkey | sudo gpg --no-tty --batch --dearmor -o /etc/apt/keyrings/opentofu-repo.gpg >/dev/null
          sudo chmod a+r /etc/apt/keyrings/opentofu.gpg /etc/apt/keyrings/opentofu-repo.gpg
          echo \
            "deb [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main
          deb-src [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main" | \
            sudo tee /etc/apt/sources.list.d/opentofu.list > /dev/null
          sudo chmod a+r /etc/apt/sources.list.d/opentofu.list
          sudo apt-get update
          sudo apt-get install -y tofu
          
      - name: Set TF_VAR_file_name
        run: |
          export TF_VAR_file_name=${{ matrix.lambda }}
          echo "TF_VAR_file_name=${{ matrix.lambda }}" >> $GITHUB_ENV

      - name: Get GitHub version
        id: get-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Set TF_VAR_folder_name
        run: |
          echo "TF_VAR_state_bucket_name=${{ secrets.STATE_BUCKET_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_bucket_name=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_region=${{ vars.AWS_REGION }}" >> $GITHUB_ENV

      - name: Set stack name
        run: |
          echo "STACK_NAME=${{ matrix.lambda }}" >> $GITHUB_ENV

      - name: Select or create stack
        run: |
          tofu stack init "$STACK_NAME" || true
          tofu stack select "$STACK_NAME"

      - name: Deploy Lambda
        run: |
          tofu apply -auto-approve \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}"
      - name: Deploy Lambda
        run: |
          tofu apply -auto-approve \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" 
